version: '3.9'

services:
  # docker-compose up --build
  # docker ps
  frontend:
    build: ./web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env.local
    environment:
      - NODE_ENV=production
  backend:
    build: ./backend
    ports:
      - "3005:3005"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production