import { API_BASE_URL, STRIPE_PK_KEY, TEST,
    FIREBASE_AUTH_API_KEY, FIREBASE_AUTH_AUTH_DOMAIN, FIREBASE_AUTH_PROJECTID,
    FIREBASE_AUTH_STORAGEBUCKET, FIREBASE_AUTH_MESSAGINGSENDERID, 
    FIREBASE_AUTH_APPID, FIREBASE_AUTH_MEASUREMENTID
} from '@env';

// console.log("API_BASE_URL: " + API_BASE_URL) // Refresh
const Env = {
    API_BASE_URL: API_BASE_URL,
    STRIPE_PK_KEY: STRIPE_PK_KEY,
    FIREBASE_AUTH_API_KEY: FIREBASE_AUTH_API_KEY,
    FIREBASE_AUTH_AUTH_DOMAIN: FIREBASE_AUTH_AUTH_DOMAIN,
    FIREBASE_AUTH_PROJECTID: FIREBASE_AUTH_PROJECTID,
    FIREBASE_AUTH_STORAGEBUCKET: FIREBASE_AUTH_STORAGEBUCKET,
    FIREBASE_AUTH_MESSAGINGSENDERID: FIREBASE_AUTH_MESSAGINGSENDERID,
    FIREBASE_AUTH_APPID: FIREBASE_AUTH_APPID,
    FIREBASE_AUTH_MEASUREMENTID: FIREBASE_AUTH_MEASUREMENTID,
}
// console.log(Env) // Refresh

export default Env;
