
// Mock Events Data => router.get("api/events/MockData")
export const mockEvents = [
  {
    id: "evt_KAx2B7mZ5u2QvF2L",
    name: "Sunset Rooftop Portrait Session",
    host: ["usr_hY9zPnmq73Ro5aU5", "usr_dL8oVxwZ8Mea43Lk"],
    session: [
      {
        sessionID: "sess_fL4mJoTtYcwFq8q1",
        startDate: "2025-04-10T08:00:00",
        endDate: "2025-04-10T10:00:00",
        price: 120.0,
        type: "Normal",
        remain: 0,
        available: 5,
      },
      {
        sessionID: "sess_hQ7kNzLmBpy93KrX",
        startDate: "2025-04-10T13:00:00",
        endDate: "2025-04-10T15:00:00",
        price: 120.0,
        type: "Golden",
        remain: 2,
        available: 3,
      },
      {
        sessionID: "sess_bR2cLuWzGtsmT9Av",
        startDate: "2025-04-10T18:00:00",
        endDate: "2025-04-10T20:00:00",
        price: 120.0,
        type: "Golden",
        remain: 2,
        available: 4,
      },
    ],
    location: {
      name: "Studio Aurora Rooftop",
      address: "1234 Sunset Blvd, Toronto, ON, Canada",
    },
    notice: {
      inPerson: true,
      indoor: false,
      outdoor: true,
      online: false,
      parking: true,
    },
    tags: ["Portraits", "Outdoor", "Golden Hour", "Canada Events"],
    eventDetail:
      "<h2><strong style='color: #e67e22;'>Join our rooftop portrait shoot!</strong></h2><p>Capture stunning portraits with golden-hour light. <a href='https://example.com'>Book Now</a></p><iframe width='325' height='315' src='https://www.youtube.com/embed/dQw4w9WgXcQ' frameborder='0' allowfullscreen></iframe>",
    imagesURL: [
      "https://secure.meetupstatic.com/photos/event/9/6/0/3/600_526478403.webp?w=750",
      "https://secure.meetupstatic.com/photos/event/9/6/0/3/600_526478403.webp?w=750",
      "https://secure.meetupstatic.com/photos/event/9/6/0/3/600_526478403.webp?w=750",
    ],
    createUser: "usr_admin_0n7R8uTaY5KvMtVz",
    createAt: "2025-03-21T10:00:00",
    logUser: "usr_firebase_fX81vTpJrQoZbZkK",
    updateAt: "2025-03-21T12:30:00",
  },
  {
    id: "evt_Z91aWkLtPq7NxV2R",
    name: "Indoor Product Photography Workshop",
    host: ["usr_x91Lo3ZsRkQwEi7T"],
    session: [
      {
        sessionID: "sess_Uo47PxkMG9aeZtP9",
        startDate: "2025-05-05T10:00:00",
        endDate: "2025-05-05T13:00:00",
        price: 90.0,
        type: "Normal",
        remain: 2,
        available: 10,
      },
    ],
    location: {
      name: "Studio BeamBox",
      address: "88 Front St E, Toronto, ON, Canada",
    },
    notice: {
      inPerson: true,
      indoor: true,
      outdoor: false,
      online: false,
      parking: true,
    },
    tags: ["Product", "Indoor", "Workshop", "Lighting"],
    eventDetail:
      "<h2><strong>Master indoor lighting</strong></h2><p>Hands-on practice with real product setups. Bring your camera!</p>",
    imagesURL: [
      "https://example.com/images/product1.jpg",
      "https://example.com/images/product2.jpg",
    ],
    createUser: "usr_creator_Wq37VmTk8qPpZo29",
    createAt: "2025-03-25T09:15:00",
    logUser: "usr_firebase_aa2KmYt8DsweXx55",
    updateAt: "2025-03-25T10:00:00",
  },
  {
    id: "evt_Nn4KeXq83zQ9TuFb",
    name: "Live DJ Set Night — Downtown Loft",
    host: ["usr_dj789TyRnLkUi23X"],
    session: [
      {
        sessionID: "sess_Lp99MwTtGhiUo0Wx",
        startDate: "2025-06-01T19:00:00",
        endDate: "2025-06-01T23:00:00",
        price: 25.0,
        type: "Normal",
        remain: 28,
        available: 30,
      },
    ],
    location: {
      name: "Loft Vibe Studio",
      address: "500 Queen St W, Toronto, ON, Canada",
    },
    notice: {
      inPerson: true,
      indoor: true,
      outdoor: false,
      online: false,
      parking: false,
    },
    tags: ["Music", "DJ", "Party", "Indoor", "Nightlife"],
    eventDetail:
      "<h2><strong>Live Music & Loft Vibes</strong></h2><p>Join Toronto's underground music scene. Dance, vibe, and network!</p><iframe width='325' height='315' src='https://www.youtube.com/embed/YOUR_VIDEO_ID' frameborder='0' allowfullscreen></iframe>",
    imagesURL: [
      "https://example.com/images/dj1.jpg",
      "https://example.com/images/dj2.jpg",
    ],
    createUser: "usr_admin_KxLm48Zq1pJwMeN2",
    createAt: "2025-03-28T18:00:00",
    logUser: "usr_firebase_gQ8LtOp9RkzzYy71",
    updateAt: "2025-03-28T18:30:00",
  },
  {
    id: "evt_Qa7TkPzMu98NzXbE",
    name: "Sunrise Landscape Photography Hike",
    host: ["usr_hike_Y2wPqXj89LkRt12A"],
    session: [
      {
        sessionID: "sess_LkW9XzQyTt8VaZcP",
        startDate: "2025-07-12T05:30:00",
        endDate: "2025-07-12T09:00:00",
        price: 60.0,
        type: "Normal",
        remain: 6,
        available: 10,
      },
    ],
    location: {
      name: "High Park Nature Trail",
      address: "1873 Bloor St W, Toronto, ON, Canada",
    },
    notice: {
      inPerson: true,
      indoor: false,
      outdoor: true,
      online: false,
      parking: true,
    },
    tags: ["Landscape", "Outdoor", "Hiking", "Sunrise", "Nature"],
    eventDetail:
      "<p>Explore Toronto's nature trails while capturing sunrise landscapes. Don't forget your tripod!</p>",
    imagesURL: [
      "https://example.com/images/hike1.jpg",
      "https://example.com/images/hike2.jpg",
    ],
    createUser: "usr_admin_JtOpZkMx29KwLp88",
    createAt: "2025-03-29T06:00:00",
    logUser: "usr_firebase_kZ9LmTpWxqPoNz39",
    updateAt: "2025-03-29T07:00:00",
  },
  {
    id: "evt_OnlineLecture_84593xZp",
    name: "How to Start Your Freelance Photography Business",
    host: ["usr_host_online_ZkPxLq92"],
    session: [
      {
        sessionID: "sess_web_12345",
        startDate: "2025-08-01T19:00:00",
        endDate: "2025-08-01T20:30:00",
        price: 0.0,
        type: "Normal",
        remain: 999,
        available: 1000,
      },
    ],
    location: {
      name: "Online Zoom Webinar",
      address: "https://zoom.us/webinar/123456789",
    },
    notice: {
      inPerson: false,
      indoor: false,
      outdoor: false,
      online: true,
      parking: false,
    },
    tags: ["Online", "Business", "Lecture", "Free", "Photography Tips"],
    eventDetail:
      "<h2>Kickstart your freelance journey</h2><p>Join our free webinar to learn how to get clients, set prices, and build your brand.</p>",
    imagesURL: [
      "https://example.com/images/webinar1.jpg",
    ],
    createUser: "usr_admin_FreeTalk123",
    createAt: "2025-03-30T10:10:00",
    logUser: "usr_firebase_OnFree789",
    updateAt: "2025-03-30T11:00:00",
  },
  {
    id: "evt_WeddingShoot_98345qPz",
    name: "Wedding Portfolio Shoot – Indoor & Outdoor",
    host: ["usr_photographer_BrideStory88"],
    session: [
      {
        sessionID: "sess_wedding_AM1",
        startDate: "2025-07-20T11:00:00",
        endDate: "2025-07-20T15:00:00",
        price: 150.0,
        type: "Normal",
        remain: 1,
        available: 5,
      },
    ],
    location: {
      name: "Evergreen Brick Works",
      address: "550 Bayview Ave, Toronto, ON, Canada",
    },
    notice: {
      inPerson: true,
      indoor: true,
      outdoor: true,
      online: false,
      parking: true,
    },
    tags: ["Wedding", "Portfolio", "Indoor", "Outdoor", "Client Practice"],
    eventDetail:
      "<p>Join our styled wedding shoot with models and props to build your portfolio.</p>",
    imagesURL: [
      "https://example.com/images/wedding1.jpg",
      "https://example.com/images/wedding2.jpg",
    ],
    createUser: "usr_admin_BWPhoto098",
    createAt: "2025-03-31T15:45:00",
    logUser: "usr_firebase_WedXy123",
    updateAt: "2025-03-31T16:00:00",
  },
];
